version: "3"

vars:
  BINARY_NAME: do-firewall-allowlister
  MAIN_PATH: ./cmd/do-firewall-allowlister
  BUILD_DIR: ./dist
  DOCKER_IMAGE: ghcr.io/kholisrag/do-firewall-allowlister
  VERSION:
    sh: git describe --tags --always --dirty 2>/dev/null || echo "dev"

env:
  CGO_ENABLED: 0
  GOOS: "{{.GOOS | default OS}}"
  GOARCH: "{{.GOARCH | default ARCH}}"

tasks:
  default:
    desc: Show available tasks
    cmds:
      - task --list

  clean:
    desc: Clean build artifacts
    cmds:
      - rm -rf {{.BUILD_DIR}}
      - rm -f {{.BINARY_NAME}}
      - go clean
      - docker system prune -f --filter label=stage=builder 2>/dev/null || true

  clean:cache:
    desc: Clean build artifacts and Go cache
    cmds:
      - task: clean
      - go clean -cache

  deps:
    desc: Download and tidy dependencies
    cmds:
      - go mod download
      - go mod tidy

  fmt:
    desc: Format Go code
    cmds:
      - go fmt ./...
      - gofumpt -w . 2>/dev/null || true

  lint:
    desc: Run linters
    cmds:
      - go vet ./...
      - golangci-lint run 2>/dev/null || echo "golangci-lint not installed, skipping"

  test:
    desc: Run tests
    cmds:
      - go test -race -coverprofile=coverage.out ./...

  test:short:
    desc: Run short tests
    cmds:
      - go test -short -race ./...

  test:integration:
    desc: Run integration tests
    cmds:
      - go test -tags=integration ./test/...

  test:coverage:
    desc: Run tests with coverage report
    deps: [test]
    cmds:
      - go tool cover -html=coverage.out -o coverage.html
      - echo "Coverage report generated{{":"}} coverage.html"

  build:
    desc: Build binary for current platform using GoReleaser
    deps: [deps]
    cmds:
      - goreleaser build --single-target --snapshot --clean

  build:all:
    desc: Build binaries for all platforms using GoReleaser
    deps: [clean, deps]
    cmds:
      - goreleaser build --snapshot --clean

  build:linux:
    desc: Build all binaries (includes Linux) using GoReleaser
    deps: [build:all]

  build:darwin:
    desc: Build all binaries (includes macOS) using GoReleaser
    deps: [build:all]

  build:windows:
    desc: Build all binaries (includes Windows) using GoReleaser
    deps: [build:all]

  docker:build:
    desc: Build Docker image
    cmds:
      - docker build -t {{.DOCKER_IMAGE}}:{{.VERSION}} -t {{.DOCKER_IMAGE}}:latest .

  docker:run:
    desc: Run Docker container
    deps: [docker:build]
    cmds:
      - docker run --rm -it {{.DOCKER_IMAGE}}:latest --help

  docker:push:
    desc: Push Docker image
    deps: [docker:build]
    cmds:
      - docker push {{.DOCKER_IMAGE}}:{{.VERSION}}
      - docker push {{.DOCKER_IMAGE}}:latest

  release:dry:
    desc: Dry run release with GoReleaser
    cmds:
      - goreleaser release --snapshot --clean --skip=publish --skip=docker

  release:
    desc: Create release with GoReleaser
    cmds:
      - goreleaser release --clean

  dev:
    desc: Run in development mode
    deps: [build]
    cmds:
      - |
        BINARY_PATH=$(find {{.BUILD_DIR}} -name "{{.BINARY_NAME}}" -type f | head -1)
        if [ -n "$BINARY_PATH" ]; then
          "$BINARY_PATH" --help
        else
          echo "Binary not found in {{.BUILD_DIR}}"
          exit 1
        fi

  install:
    desc: Install binary to GOPATH/bin
    deps: [build]
    cmds:
      - go install {{.MAIN_PATH}}

  validate:
    desc: Validate configuration
    deps: [build]
    cmds:
      - |
        BINARY_PATH=$(find {{.BUILD_DIR}} -name "{{.BINARY_NAME}}" -type f | head -1)
        if [ -n "$BINARY_PATH" ]; then
          "$BINARY_PATH" validate --config config.yaml
        else
          echo "Binary not found in {{.BUILD_DIR}}"
          exit 1
        fi

  check:
    desc: Run all checks (format, lint, test)
    cmds:
      - task: fmt
      - task: lint
      - task: test:short

  ci:
    desc: Run CI pipeline
    cmds:
      - task: deps
      - task: fmt
      - task: lint
      - task: test
      - task: build:all
